config/routes.rb
CompassUp::Application.routes.draw do

  resources :ais_terms do
    member do
      get :delete
    end
  end

  resources :ais_checklists do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_attributes do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_application_comments do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  root :to => 'welcome#index'

end

app/models/ais_application_comment.rb
class AisApplicationComment < ActiveRecord::Base
  attr_accessible :application_number, :application_term, :banner_pidm, :comment, :originator
  
  validates :application_number, :application_term, :banner_pidm, :originator, presence: true
  
  # BannerPIDM^ApplicationTerm^ApplicationNumber^Originator^Comment
  def self.import(file, terms = [])
    spreadsheet = open_spreadsheet(file)
    header = ["banner_pidm", "application_term", "application_number", "originator", "comment"]
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      record = new
      record.attributes = row.to_hash.slice(*accessible_attributes)
      record.save! if terms.include?(record.application_term)
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename).downcase
      when ".csv" then Roo::Csv.new(file.path, csv_options: {col_sep: "^"})
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else 
      raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/controllers/ais_application_comments_controller.rb
class AisApplicationCommentsController < ApplicationController
  # GET /ais_application_comments
  # GET /ais_application_comments.json
  def index
    @ais_application_comments = AisApplicationComment.order("id").page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ais_application_comments }
    end
  end

  # GET /ais_application_comments/1
  # GET /ais_application_comments/1.json
  def show
    @ais_application_comment = AisApplicationComment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ais_application_comment }
    end
  end

  # GET /ais_application_comments/new
  # GET /ais_application_comments/new.json
  def new
    @ais_application_comment = AisApplicationComment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ais_application_comment }
    end
  end

  # GET /ais_application_comments/1/edit
  def edit
    @ais_application_comment = AisApplicationComment.find(params[:id])
  end

  # POST /ais_application_comments
  # POST /ais_application_comments.json
  def create
    @ais_application_comment = AisApplicationComment.new(params[:ais_application_comment])

    respond_to do |format|
      if @ais_application_comment.save
        format.html { redirect_to @ais_application_comment, notice: 'Record was successfully created.' }
        format.json { render json: @ais_application_comment, status: :created, location: @ais_application_comment }
      else
        format.html { render action: "new" }
        format.json { render json: @ais_application_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ais_application_comments/1
  # PUT /ais_application_comments/1.json
  def update
    @ais_application_comment = AisApplicationComment.find(params[:id])

    respond_to do |format|
      if @ais_application_comment.update_attributes(params[:ais_application_comment])
        format.html { redirect_to @ais_application_comment, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ais_application_comment.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # GET /ais_application_comments/1/are_you_sure
  def are_you_sure
    @ais_application_comment = AisApplicationComment.find(params[:id])
  end

  # DELETE /ais_application_comments/1
  # DELETE /ais_application_comments/1.json
  def destroy
    @ais_application_comment = AisApplicationComment.find(params[:id])
    @ais_application_comment.destroy

    respond_to do |format|
      format.html { redirect_to ais_application_comments_url, notice: 'Record was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  def show_import
  end
  
  def import
    if params[:file] && params[:spring_term] && params[:summer_term] && params[:fall_term]
      AisApplicationComment.delete_all
      AisApplicationComment.import(params[:file], [params[:spring_term], params[:summer_term], params[:fall_term]])
      redirect_to ais_application_comments_url, notice: "Records imported."
    else
      redirect_to show_import_ais_application_comments_path, alert: "Please enter all terms and select a file."
    end
  end  
  
end

app/helpers/ais_application_comments_helper.rb
module AisApplicationCommentsHelper
end

app/views/ais_application_comments/_details.html.erb
<dl class="dl-horizontal">
  <dt>PIDM</dt>
  <dd><%= @ais_application_comment.banner_pidm %></dd>
  <dt>Term</dt>
  <dd><%= @ais_application_comment.application_term %></dd>
  <dt>Application No.</dt>
  <dd><%= @ais_application_comment.application_number %></dd>
  <dt>Originator</dt>
  <dd><%= @ais_application_comment.originator %></dd>
  <dt>Comment</dt>
  <dd><%= @ais_application_comment.comment %></dd>
</dl>

app/views/ais_application_comments/_form.html.erb
<%= bootstrap_form_for @ais_application_comment do |f| %>

  <%= f.error_messages %>

	<%= f.bs_text_field :banner_pidm, label: "PIDM", placeholder: "PIDM", help_text: "Required." %>
	
	<%= f.bs_text_field :application_term, label: "Term", placeholder: "Term", help_text: "Required." %>
	
	<%= f.bs_text_field :application_number, label: "Application No.", placeholder: "Application No.", help_text: "Required." %>

	<%= f.bs_text_field :originator, placeholder: "Originator", help_text: "Required." %>

	<%= f.bs_text_area :comment, placeholder: "Comment" %>

  <%= f.bs_submit "Submit" %>

<% end %>

app/views/ais_application_comments/are_you_sure.html.erb
<div class="page-header">
  <h2>Delete AIS Application Comment</h2>
</div>

<ul class="nav nav-tabs">
	<li>
		<%= link_to ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-list"></span> List
		<% end -%>
	</li>
	<li>
		<%= link_to @ais_application_comment do -%>
		   <span class="glyphicon glyphicon-info-sign"></span> Details
		<% end -%>
	</li>
	<li>
		<%= link_to edit_ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-pencil"></span> Edit
		<% end -%>
	</li>
	<li class="active">
		<%= link_to are_you_sure_ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-remove"></span> Delete
		<% end -%>
	</li>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning, you are about to delete the following record.</h3>
  </div>
  <div class="panel-body">
		<%= render 'details' %>
	  <div class="row">
			<div class="col-sm-offset-2 col-sm-10">
				<%= link_to @ais_application_comment, class: "btn btn-default btn-danger", method: :delete do -%>
				<span class="glyphicon glyphicon-remove"></span> Delete
				<% end -%>
				<%= link_to "Cancel", :back, class: "btn btn-default" %>
			</div>
	  </div>
	</div>
</div>

app/views/ais_application_comments/edit.html.erb
<div class="page-header">
  <h2>Update AIS Application Comment</h2>
</div>

<ul class="nav nav-tabs">
	<li>
		<%= link_to ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-list"></span> List
		<% end -%>
	</li>
	<li>
		<%= link_to @ais_application_comment do -%>
		   <span class="glyphicon glyphicon-info-sign"></span> Details
		<% end -%>
	</li>
	<li class="active">
		<%= link_to edit_ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-pencil"></span> Edit
		<% end -%>
	</li>
	<li>
		<%= link_to are_you_sure_ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-remove"></span> Delete
		<% end -%>
	</li>
</ul>

<%= render 'form' %>

app/views/ais_application_comments/index.html.erb
<div class="page-header">
  <h2>AIS Application Comments</h2>
</div>

<ul class="nav nav-tabs">
	<li class="active">
		<%= link_to ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-list"></span> List
		<% end -%>
	</li>
	<li>
		<%= link_to new_ais_application_comment_path do -%>
		   <span class="glyphicon glyphicon-plus"></span> Add New
		<% end -%>
	</li>
	<li>
		<%= link_to show_import_ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-import"></span> Import
		<% end -%>
	</li>
</ul>

<table class="table table-condensed table-striped table-hover">
	<thead>
	  <tr>
	    <th>PIDM</th>
	    <th>Term</th>
	    <th>Application No.</th>
	    <th>Originator</th>
	    <th>Comment</th>
			
			<th class="shrink"></th>
			<th class="shrink"></th>
			<th class="shrink"></th>
	  </tr>
	</thead>

	<tbody>
		<% @ais_application_comments.each do |ais_application_comment| -%>
	  <tr>
	    <td><%= ais_application_comment.banner_pidm %></td>
	    <td><%= ais_application_comment.application_term %></td>
	    <td><%= ais_application_comment.application_number %></td>
	    <td><%= ais_application_comment.originator %></td>
	    <td><%= ais_application_comment.comment.truncate(100) if ais_application_comment.comment %></td>
			
			<td>
				<%= link_to ais_application_comment do -%>
				<span class="glyphicon glyphicon-info-sign"></span>
				<% end -%>
			</td>
			<td>
				<%= link_to edit_ais_application_comment_path(ais_application_comment) do -%>
				<span class="glyphicon glyphicon-pencil"></span>
				<% end -%>
			</td>
			<td>
				<%= link_to are_you_sure_ais_application_comment_path(ais_application_comment) do -%>
				<span class="glyphicon glyphicon-remove"></span>
				<% end -%>
			</td>
	  </tr>
		<% end -%>
	</tbody>
</table>

<div class="panel panel-default">
  <div class="panel-body">
    <%= paginate @ais_application_comments %>
  </div>
</div>

app/views/ais_application_comments/new.html.erb
<div class="page-header">
  <h2>New AIS Application Comment</h2>
</div>

<ul class="nav nav-tabs">
	<li>
		<%= link_to ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-list"></span> List
		<% end -%>
	</li>
	<li class="active">
		<%= link_to new_ais_application_comment_path do -%>
		   <span class="glyphicon glyphicon-plus"></span> Add New
		<% end -%>
	</li>
	<li>
		<%= link_to show_import_ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-import"></span> Import
		<% end -%>
	</li>
</ul>

<%= render 'form' %>

app/views/ais_application_comments/show.html.erb
<div class="page-header">
  <h2>AIS Application Comment</h2>
</div>

<ul class="nav nav-tabs">
	<li>
		<%= link_to ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-list"></span> List
		<% end -%>
	</li>
	<li class="active">
		<%= link_to ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-info-sign"></span> Details
		<% end -%>
	</li>
	<li>
		<%= link_to edit_ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-pencil"></span> Edit
		<% end -%>
	</li>
	<li>
		<%= link_to are_you_sure_ais_application_comment_path(@ais_application_comment) do -%>
		   <span class="glyphicon glyphicon-remove"></span> Delete
		<% end -%>
	</li>
</ul>

<%= render 'details' %>

app/views/ais_application_comments/show_import.html.erb
<div class="page-header">
  <h2>Import AIS Application Comments</h2>
</div>

<ul class="nav nav-tabs">
	<li>
		<%= link_to ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-list"></span> List
		<% end -%>
	</li>
	<li>
		<%= link_to new_ais_application_comment_path do -%>
		   <span class="glyphicon glyphicon-plus"></span> Add New
		<% end -%>
	</li>
	<li class="active">
		<%= link_to show_import_ais_application_comments_path do -%>
		   <span class="glyphicon glyphicon-import"></span> Import
		<% end -%>
	</li>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning! This will delete all records before importing.</h3>
  </div>
  <div class="panel-body">
		<%= form_tag import_ais_application_comments_path, multipart: true, role: "form", class: "form-horizontal" do %>
		
	  <div class="form-group">
	    <%= label_tag "spring_term-label", "Spring Term", class: "col-sm-2 control-label" %>
			<div class="col-sm-10">
		    <%= text_field_tag "spring_term", "201412", class: "form-control", placeholder: "Spring Term" %>
			</div>
	  </div>
		
	  <div class="form-group">
	    <%= label_tag "summer_term-label", "Summer Term", class: "col-sm-2 control-label" %>
			<div class="col-sm-10">
		    <%= text_field_tag "summer_term", "201422", class: "form-control", placeholder: "Summer Term" %>
			</div>
	  </div>
		
	  <div class="form-group">
	    <%= label_tag "fall_term-label", "Fall Term", class: "col-sm-2 control-label" %>
			<div class="col-sm-10">
		    <%= text_field_tag "fall_term", "201432", class: "form-control", placeholder: "Fall Term" %>
			</div>
	  </div>
		
		<div class="form-group">
			<%= label_tag "file-label", "File", class: "col-sm-2 control-label" %>
			<div class="col-sm-10">
				<%= file_field_tag :file %>
			</div>
		</div>
		
	  <div class="form-group">
			<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-danger" name="commit"><span class="glyphicon glyphicon-import"></span> Import</button>
			</div>
	  </div>
		
		<% end %>
	</div>
</div>