config/routes.rb
CompassUp::Application.routes.draw do

  resources :ais_terms do
    member do
      get :delete
    end
  end

  resources :ais_checklists do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_attributes do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_application_comments do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  root :to => 'welcome#index'

end

app/models/ais_checklist.rb
class AisChecklist < ActiveRecord::Base
  attr_accessible :application_number, :application_term, :banner_pidm, :ckst_code, :item, :item_description, :mandatory, :received_date, :requirement_code

  validates :banner_pidm, :application_term, :application_number, :requirement_code, presence: true
  
  # BANNERPIDM^APPLICATIONTERM^APPLICATIONNUMBER^REQUIREMENTCODE^RECEIVEDDATE^ITEM^ITEMDESCRIPTION^CKST_CODE^MANDATORY^
  def self.import(file, terms = [])
    spreadsheet = open_spreadsheet(file)
    header = ["banner_pidm", "application_term", "application_number", "requirement_code", "received_date", "item", "item_description", "ckst_code", "mandatory"]
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      record = new
      record.attributes = row.to_hash.slice(*accessible_attributes)
      record.save! if terms.include?(record.application_term)
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename).downcase
      when ".csv" then Roo::Csv.new(file.path, csv_options: {col_sep: "^"})
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else 
      raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/controllers/ais_checklists_controller.rb
class AisChecklistsController < ApplicationController
  # GET /ais_checklists
  # GET /ais_checklists.json
  def index
    @ais_checklists = AisChecklist.order("id").page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ais_checklists }
    end
  end

  # GET /ais_checklists/1
  # GET /ais_checklists/1.json
  def show
    @ais_checklist = AisChecklist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ais_checklist }
    end
  end

  # GET /ais_checklists/new
  # GET /ais_checklists/new.json
  def new
    @ais_checklist = AisChecklist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ais_checklist }
    end
  end

  # GET /ais_checklists/1/edit
  def edit
    @ais_checklist = AisChecklist.find(params[:id])
  end

  # POST /ais_checklists
  # POST /ais_checklists.json
  def create
    @ais_checklist = AisChecklist.new(params[:ais_checklist])

    respond_to do |format|
      if @ais_checklist.save
        format.html { redirect_to @ais_checklist, notice: 'Record was successfully created.' }
        format.json { render json: @ais_checklist, status: :created, location: @ais_checklist }
      else
        format.html { render action: "new" }
        format.json { render json: @ais_checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ais_checklists/1
  # PUT /ais_checklists/1.json
  def update
    @ais_checklist = AisChecklist.find(params[:id])

    respond_to do |format|
      if @ais_checklist.update_attributes(params[:ais_checklist])
        format.html { redirect_to @ais_checklist, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ais_checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /@ais_checklists/1/are_you_sure
  def are_you_sure
    @ais_checklist = AisChecklist.find(params[:id])
  end

  # DELETE /ais_checklists/1
  # DELETE /ais_checklists/1.json
  def destroy
    @ais_checklist = AisChecklist.find(params[:id])
    @ais_checklist.destroy

    respond_to do |format|
      format.html { redirect_to ais_checklists_url, notice: 'Record was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def show_import
  end
  
  def import
    if params[:file] && params[:spring_term] && params[:summer_term] && params[:fall_term]
      AisChecklist.delete_all
      AisChecklist.import(params[:file], [params[:spring_term], params[:summer_term], params[:fall_term]])
      redirect_to ais_checklist_url, notice: "Records imported."
    else
      redirect_to show_import_ais_checklist_path, alert: "Please enter all terms and select a file."
    end
  end  

end

app/helpers/ais_checklists_helper.rb
module AisChecklistsHelper
end

app/views/ais_checklists/_details.html.erb
<dl class="dl-horizontal">
  <dt>PIDM</dt>
  <dd><%= @ais_checklist.banner_pidm %></dd>
  <dt>Term</dt>
  <dd><%= @ais_checklist.application_term %>/dd>
  <dt>Application No.</dt>
  <dd><%= @ais_checklist.application_number %></dd>
  <dt>Requirement Code</dt>
  <dd><%= @ais_checklist.requirement_code %></dd>
  <dt>Received Date</dt>
  <dd><%= @ais_checklist.received_date %></dd>
  <dt>Item</dt>
  <dd><%= @ais_checklist.item %></dd>
  <dt>Item Description</dt>
  <dd><%= @ais_checklist.item_description %></dd>
  <dt>CKST Code</dt>
  <dd><%= @ais_checklist.ckst_code %></dd>
  <dt>Mandatory</dt>
  <dd><%= @ais_checklist.mandatory %></dd>
</dl>

app/views/ais_checklists/_form.html.erb
<%= bootstrap_form_for @ais_checklist do |f| %>
  
	<%= f.error_messages %>

	<%= f.bs_text_field :banner_pidm, label: "PIDM", placeholder: "PIDM", help_text: "Required." %>
	
	<%= f.bs_text_field :application_term, label: "Term", placeholder: "Term", help_text: "Required." %>
	
	<%= f.bs_text_field :application_number, label: "Application No.", placeholder: "Application No.", help_text: "Required." %>

	<%= f.bs_text_field :requirement_code, label: "Requirement Code", placeholder: "Requirement Code", help_text: "Required." %>

	<%= f.bs_text_field :received_date, label: "Received Date", placeholder: "Received Date" %>

	<%= f.bs_text_field :item, placeholder: "Received Date" %>

	<%= f.bs_text_field :item_description, label: "Item Description", placeholder: "Item Description" %>

	<%= f.bs_text_field :ckst_code, label: "CKST Code", placeholder: "CKST Code" %>

	<%= f.bs_text_field :mandatory, placeholder: "Mandatory" %>

  <%= f.bs_submit "Submit" %>
	
<% end %>

app/views/ais_checklists/are_you_sure.html.erb
<div class="page-header">
  <h2>Delete AIS Checklist</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_checklist, "Details", "glyphicon-info-sign" %>
	<%= nav_tab_link_to edit_ais_checklist_path(@ais_checklist), "Edit", "glyphicon-pencil" %>
	<%= nav_tab_link_to are_you_sure_ais_checklist_path(@ais_checklist), "Delete", "glyphicon-remove", class: "active" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import" %>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning, you are about to delete the following record.</h3>
  </div>
  <div class="panel-body">
		<%= render 'details' %>
	  <div class="row">
			<div class="col-sm-offset-2 col-sm-10">
				<%= link_to @ais_checklist, class: "btn btn-danger", method: :delete do -%>
				<span class="glyphicon glyphicon-remove"></span> Delete
				<% end -%>
				<%= link_to "Cancel", :back, class: "btn btn-default" %>
			</div>
	  </div>
	</div>
</div>

app/views/ais_checklists/edit.html.erb
<div class="page-header">
  <h2>Update AIS Checklist</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_checklist, "Details", "glyphicon-info-sign" %>
	<%= nav_tab_link_to edit_ais_checklist_path(@ais_checklist), "Edit", "glyphicon-pencil", class: "active" %>
	<%= nav_tab_link_to are_you_sure_ais_checklist_path(@ais_checklist), "Delete", "glyphicon-remove" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import" %>
</ul>

<%= render 'form' %>

app/views/ais_checklists/index.html.erb
<div class="page-header">
  <h2>AIS Checklists</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list", class: "active" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import" %>
</ul>

<table class="table table-condensed table-striped table-hover">
	<thead>
	  <tr>
	    <th>PIDM</th>
	    <th>Term</th>
	    <th>Application No.</th>
	    <th>Requirement Code</th>
	    <th>Received Date</th>
	    <th>Item</th>
	    <th>Description</th>
	    <th>CKST Code</th>
	    <th>Mandatory</th>
			
			<th class="shrink"></th>
			<th class="shrink"></th>
			<th class="shrink"></th>
	  </tr>
	</thead>

	<tbody>
		<% @ais_checklists.each do |ais_checklist| %>
		  <tr>
		    <td><%= ais_checklist.banner_pidm %></td>
		    <td><%= ais_checklist.application_term %></td>
		    <td><%= ais_checklist.application_number %></td>
		    <td><%= ais_checklist.requirement_code %></td>
		    <td><%= ais_checklist.received_date %></td>
		    <td><%= ais_checklist.item %></td>
		    <td><%= ais_checklist.item_description %></td>
		    <td><%= ais_checklist.ckst_code %></td>
		    <td><%= ais_checklist.mandatory %></td>
			
				<td>
					<%= link_to ais_checklist do -%>
					<span class="glyphicon glyphicon-info-sign"></span>
					<% end -%>
				</td>
				<td>
					<%= link_to edit_ais_checklist_path(ais_checklist) do -%>
					<span class="glyphicon glyphicon-pencil"></span>
					<% end -%>
				</td>
				<td>
					<%= link_to are_you_sure_ais_checklist_path(ais_checklist) do -%>
					<span class="glyphicon glyphicon-remove"></span>
					<% end -%>
				</td>
		  </tr>
		<% end %>
	</tbody>
</table>

	
	<div class="panel panel-default">
		<div class="panel-footer">
			<%= paginate @ais_checklists %>
		</div>
	</div>

app/views/ais_checklists/new.html.erb
<div class="page-header">
  <h2>New AIS Checklist</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus", class: "active" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import" %>
</ul>

<%= render 'form' %>

app/views/ais_checklists/show.html.erb
<div class="page-header">
  <h2>AIS Checklist</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_checklist, "Details", "glyphicon-info-sign", class: "active" %>
	<%= nav_tab_link_to edit_ais_checklist_path(@ais_checklist), "Edit", "glyphicon-pencil" %>
	<%= nav_tab_link_to are_you_sure_ais_checklist_path(@ais_checklist), "Delete", "glyphicon-remove" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import" %>
</ul>

<%= render 'details' %>

app/views/ais_checklists/show_import.html.erb
<div class="page-header">
  <h2>Import AIS Checlists</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import", class: "active" %>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning! This will delete all records before importing.</h3>
  </div>
  <div class="panel-body">
		<%= form_tag import_ais_checklists_path, multipart: true, role: "form", class: "form-inline" do %>
			<div class="form-group">
				<%= file_field_tag :file %>
			</div>
			<button type="submit" class="btn btn-default btn-danger" name="commit">Import</button>
		<% end %>
	</div>
</div>