config/routes.rb
CompassUp::Application.routes.draw do

  resources :ais_terms do
    member do
      get :delete
    end
  end

  resources :ais_checklists do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_attributes do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_application_comments do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  root :to => 'welcome#index'

end

app/models/ais_term.rb
class AisTerm < ActiveRecord::Base
  attr_accessible :effective_on, :fall, :spring, :summer
  
  validates :effective_on, uniqueness: true
  validates :effective_on, timeliness: { type: :date }  
  validates :effective_on, :fall, :spring, :summer, presence: true
  validates :fall, :spring, :summer, length: { is: 6 }
  validates :fall, :spring, :summer, numericality: { only_integer: true }
  validate :spring_summer_and_fall_must_be_same_year
  
  default_scope order('effective_on DESC')
  
  def self.current
    where('effective_on <= ?', Date.today).first
  end
  
  def is_current?
    self.eql?(AisTerm.current)
  end
  
  def spring_summer_and_fall_must_be_same_year
    year = spring[0..3]
    unless summer.start_with?(year) && fall.start_with?(year)
      errors.add(:spring, "Summer and Fall must be same year")
    end
  end
  
end

app/controllers/ais_terms_controller.rb
class AisTermsController < ApplicationController
  # GET /ais_terms
  # GET /ais_terms.json
  def index
    @ais_terms = AisTerm.page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ais_terms }
    end
  end

  # GET /ais_terms/1
  # GET /ais_terms/1.json
  def show
    @ais_term = AisTerm.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ais_term }
    end
  end

  # GET /ais_terms/new
  # GET /ais_terms/new.json
  def new
    @ais_term = AisTerm.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ais_term }
    end
  end

  # GET /ais_terms/1/edit
  def edit
    @ais_term = AisTerm.find(params[:id])
  end

  # POST /ais_terms
  # POST /ais_terms.json
  def create
    @ais_term = AisTerm.new(params[:ais_term])

    respond_to do |format|
      if @ais_term.save
        format.html { redirect_to @ais_term, notice: 'Ais term was successfully created.' }
        format.json { render json: @ais_term, status: :created, location: @ais_term }
      else
        format.html { render action: "new" }
        format.json { render json: @ais_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ais_terms/1
  # PUT /ais_terms/1.json
  def update
    @ais_term = AisTerm.find(params[:id])

    respond_to do |format|
      if @ais_term.update_attributes(params[:ais_term])
        format.html { redirect_to @ais_term, notice: 'Ais term was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ais_term.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /@ais_checklists/1/delete
  def delete
    @ais_term = AisTerm.find(params[:id])
  end

  # DELETE /ais_terms/1
  # DELETE /ais_terms/1.json
  def destroy
    @ais_term = AisTerm.find(params[:id])
    @ais_term.destroy

    respond_to do |format|
      format.html { redirect_to ais_terms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ais_terms_helper.rb
module AisTermsHelper
end

app/views/ais_terms/_details.html.erb
<dl class="dl-horizontal">
  <dt>Effective On</dt>
  <dd><%= @ais_term.effective_on %></dd>
  <dt>Spring</dt>
  <dd><%= @ais_term.spring %></dd>
  <dt>Summer</dt>
  <dd><%= @ais_term.summer %></dd>
  <dt>Fall</dt>
  <dd><%= @ais_term.fall %></dd>
</dl>

app/views/ais_terms/_form.html.erb
<%= bootstrap_form_for @ais_term do |f| %>
  
	<%= f.error_messages %>

	<%= f.bs_text_field :effective_on, label: "Effective On", placeholder: "Effective On", help_text: "Required. Format: yyyy-mm-dd" %>
	
	<%= f.bs_text_field :spring, placeholder: "Spring", help_text: "Required." %>
	
	<%= f.bs_text_field :summer, placeholder: "Summer", help_text: "Required." %>
	
	<%= f.bs_text_field :fall, placeholder: "Fall", help_text: "Required." %>
	
  <%= f.bs_submit "Submit" %>
	
<% end %>

app/views/ais_terms/delete.html.erb
<div class="page-header">
  <h2>Delete AIS Term</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_terms_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_term_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_term, "Details", "glyphicon-info-sign" %>
	<%= nav_tab_link_to edit_ais_term_path(@ais_term), "Edit", "glyphicon-pencil" %>
	<%= nav_tab_link_to delete_ais_term_path(@ais_term), "Delete", "glyphicon-remove", class: "active" %>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning, you are about to delete the following record.</h3>
  </div>
  <div class="panel-body">
		<%= render 'details' %>
	  <div class="row">
			<div class="col-sm-offset-2 col-sm-10">
				<%= link_to @ais_term, class: "btn btn-danger", method: :delete do -%>
				<span class="glyphicon glyphicon-remove"></span> Delete
				<% end -%>
				<%= link_to "Cancel", :back, class: "btn btn-default" %>
			</div>
	  </div>
	</div>
</div>

app/views/ais_terms/edit.html.erb
<div class="page-header">
  <h2>Update AIS Term</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_terms_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_term_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_term, "Details", "glyphicon-info-sign" %>
	<%= nav_tab_link_to edit_ais_term_path(@ais_term), "Edit", "glyphicon-pencil", class: "active" %>
	<%= nav_tab_link_to delete_ais_term_path(@ais_term), "Delete", "glyphicon-remove" %>
</ul>

<%= render 'form' %>

app/views/ais_terms/index.html.erb
<div class="page-header">
  <h2>AIS Terms</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_terms_path, "List", "glyphicon-list", class: "active" %>
	<%= nav_tab_link_to new_ais_term_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
</ul>

<table class="table table-condensed table-striped table-hover">
	<thead>
	  <tr>
	    <th>Effective On</th>
	    <th>Spring</th>
	    <th>Summer</th>
	    <th>Fall</th>
			
			<th class="shrink"></th>
			<th class="shrink"></th>
			<th class="shrink"></th>
	  </tr>
	</thead>

	<tbody>
		<% @ais_terms.each do |ais_term| %>
		  <% if ais_term.is_current? %><tr class="success"><% else %><tr><% end %>
		    <td><%= ais_term.effective_on %></td>
		    <td><%= ais_term.spring %></td>
		    <td><%= ais_term.summer %></td>
		    <td><%= ais_term.fall %></td>
			
				<td>
					<%= link_to ais_term do -%>
					<span class="glyphicon glyphicon-info-sign"></span>
					<% end -%>
				</td>
				<td>
					<%= link_to edit_ais_term_path(ais_term) do -%>
					<span class="glyphicon glyphicon-pencil"></span>
					<% end -%>
				</td>
				<td>
					<%= link_to delete_ais_term_path(ais_term) do -%>
					<span class="glyphicon glyphicon-remove"></span>
					<% end -%>
				</td>
		  </tr>
		<% end %>
	</tbody>
</table>

	
	<div class="panel panel-default">
		<div class="panel-footer">
			<%= paginate @ais_terms %>
		</div>
	</div>

app/views/ais_terms/new.html.erb
<div class="page-header">
  <h2>New AIS Term</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_terms_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_term_path, "Add New", "glyphicon-plus", class: "active" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
</ul>

<%= render 'form' %>

app/views/ais_terms/show.html.erb
<div class="page-header">
  <h2>AIS Term</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_terms_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_term_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_term, "Details", "glyphicon-info-sign", class: "active" %>
	<%= nav_tab_link_to edit_ais_term_path(@ais_term), "Edit", "glyphicon-pencil" %>
	<%= nav_tab_link_to delete_ais_term_path(@ais_term), "Delete", "glyphicon-remove" %>
</ul>

<%= render 'details' %>