config/routes.rb
CompassUp::Application.routes.draw do

  resources :ais_terms do
    member do
      get :delete
    end
  end

  resources :ais_checklists do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_attributes do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  resources :ais_application_comments do
    member do
      get :are_you_sure
    end
    collection do
      post :import
      get :show_import
    end    
  end

  root :to => 'welcome#index'

end

app/models/ais_attribute.rb
class AisAttribute < ActiveRecord::Base
  attr_accessible :application_number, :application_term, :name, :banner_pidm

  validates :application_number, :application_term, :name, :banner_pidm, presence: true

  # BANNERPIDM^APPLICATIONTERM^APPLICATIONNUMBER^ATTRIBUTE
  def self.import(file, terms = [])
    spreadsheet = open_spreadsheet(file)
    header = ["banner_pidm", "application_term", "application_number", "name"]
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      record = new
      record.attributes = row.to_hash.slice(*accessible_attributes)
      record.save! if terms.include?(record.application_term)
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename).downcase
      when ".csv" then Roo::Csv.new(file.path, csv_options: {col_sep: "^"})
      when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
      when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else 
       raise "Unknown file type: #{file.original_filename}"
    end
  end

end

app/controllers/ais_attributes_controller.rb
class AisAttributesController < ApplicationController
  # GET /ais_attributes
  # GET /ais_attributes.json
  def index
    @ais_attributes = AisAttribute.order("id").page params[:page]

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ais_attributes }
    end
  end

  # GET /ais_attributes/1
  # GET /ais_attributes/1.json
  def show
    @ais_attribute = AisAttribute.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ais_attribute }
    end
  end

  # GET /ais_attributes/new
  # GET /ais_attributes/new.json
  def new
    @ais_attribute = AisAttribute.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ais_attribute }
    end
  end

  # GET /ais_attributes/1/edit
  def edit
    @ais_attribute = AisAttribute.find(params[:id])
  end

  # POST /ais_attributes
  # POST /ais_attributes.json
  def create
    @ais_attribute = AisAttribute.new(params[:ais_attribute])

    respond_to do |format|
      if @ais_attribute.save
        format.html { redirect_to @ais_attribute, notice: 'Record was successfully created.' }
        format.json { render json: @ais_attribute, status: :created, location: @ais_attribute }
      else
        format.html { render action: "new" }
        format.json { render json: @ais_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ais_attributes/1
  # PUT /ais_attributes/1.json
  def update
    @ais_attribute = AisAttribute.find(params[:id])

    respond_to do |format|
      if @ais_attribute.update_attributes(params[:ais_attribute])
        format.html { redirect_to @ais_attribute, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ais_attribute.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /ais_attributes/1/are_you_sure
  def are_you_sure
    @ais_attribute = AisAttribute.find(params[:id])
  end

  # DELETE /ais_attributes/1
  # DELETE /ais_attributes/1.json
  def destroy
    @ais_attribute = AisAttribute.find(params[:id])
    @ais_attribute.destroy

    respond_to do |format|
      format.html { redirect_to ais_attributes_url, notice: 'Record was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  def show_import
  end
  
  def import
    if params[:file] && params[:spring_term] && params[:summer_term] && params[:fall_term]
      AisAttribute.delete_all
      AisAttribute.import(params[:file], [params[:spring_term], params[:summer_term], params[:fall_term]])
      redirect_to ais_attributes_url, notice: "Records imported."
    else
      redirect_to show_import_ais_attributes_path, alert: "Please enter all terms and select a file."
    end
  end  

end

app/helpers/ais_attributes_helper.rb
module AisAttributesHelper
end

app/views/ais_attributes/_details.html.erb
<dl class="dl-horizontal">
  <dt>PIDM</dt>
  <dd><%= @ais_attribute.banner_pidm %></dd>
  <dt>Term</dt>
  <dd><%= @ais_attribute.application_term %></dd>
  <dt>Application No.</dt>
  <dd><%= @ais_attribute.application_number %></dd>
  <dt>Attribute</dt>
  <dd><%= @ais_attribute.name %></dd>
</dl>

app/views/ais_attributes/_form.html.erb
<%= bootstrap_form_for @ais_attribute do |f| %>
  
	<%= f.error_messages %>

	<%= f.bs_text_field :banner_pidm, label: "PIDM", placeholder: "PIDM", help_text: "Required." %>
	
	<%= f.bs_text_field :application_term, label: "Term", placeholder: "Term", help_text: "Required." %>
	
	<%= f.bs_text_field :application_number, label: "Application No.", placeholder: "Application No.", help_text: "Required." %>
	
	<%= f.bs_text_field :name, placeholder: "Name", help_text: "Required." %>

	<%= f.bs_submit "Submit" %>
	
<% end %>

app/views/ais_attributes/are_you_sure.html.erb
<div class="page-header">
  <h2>Delete AIS Attribute</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_attributes_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_attribute_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_attribute, "Details", "glyphicon-info-sign" %>
	<%= nav_tab_link_to edit_ais_attribute_path(@ais_attribute), "Edit", "glyphicon-pencil" %>
	<%= nav_tab_link_to are_you_sure_ais_attribute_path(@ais_attribute), "Delete", "glyphicon-remove", class: "active" %>
	<%= nav_tab_link_to show_import_ais_attributes_path, "Import", "glyphicon-import" %>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning, you are about to delete the following record.</h3>
  </div>
  <div class="panel-body">
		<%= render 'details' %>
	  <div class="row">
			<div class="col-sm-offset-2 col-sm-10">
				<%= link_to @ais_attribute, class: "btn btn-default btn-danger", method: :delete do -%>
				<span class="glyphicon glyphicon-remove"></span> Delete
				<% end -%>
				<%= link_to "Cancel", :back, class: "btn btn-default" %>
			</div>
	  </div>
	</div>
</div>

app/views/ais_attributes/edit.html.erb
<div class="page-header">
  <h2>Update AIS Attribute</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_attributes_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_attribute_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_attribute, "Details", "glyphicon-info-sign" %>
	<%= nav_tab_link_to edit_ais_attribute_path(@ais_attribute), "Edit", "glyphicon-pencil", class: "active" %>
	<%= nav_tab_link_to are_you_sure_ais_attribute_path(@ais_attribute), "Delete", "glyphicon-remove" %>
	<%= nav_tab_link_to show_import_ais_attributes_path, "Import", "glyphicon-import" %>
</ul>

<%= render 'form' %>

app/views/ais_attributes/index.html.erb
<div class="page-header">
  <h2>AIS Attributes</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_attributes_path, "List", "glyphicon-list", class: "active" %>
	<%= nav_tab_link_to new_ais_attribute_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
	<%= nav_tab_link_to show_import_ais_attributes_path, "Import", "glyphicon-import" %>
</ul>

<table class="table table-condensed table-striped table-hover">
	<thead>
	  <tr>
	    <th>PIDM</th>
	    <th>Term</th>
	    <th>Application No.</th>
	    <th>Attribute</th>
			
			<th class="shrink"></th>
			<th class="shrink"></th>
			<th class="shrink"></th>
	  </tr>
	</thead>
	
	<tbody>
		<% @ais_attributes.each do |ais_attribute| %>
	  <tr>
	    <td><%= ais_attribute.banner_pidm %></td>
	    <td><%= ais_attribute.application_term %></td>
	    <td><%= ais_attribute.application_number %></td>
	    <td><%= ais_attribute.name %></td>
			
			<td>
				<%= link_to ais_attribute do -%>
				<span class="glyphicon glyphicon-info-sign"></span>
				<% end -%>
			</td>
			<td>
				<%= link_to edit_ais_attribute_path(ais_attribute) do -%>
				<span class="glyphicon glyphicon-pencil"></span>
				<% end -%>
			</td>
			<td>
				<%= link_to are_you_sure_ais_attribute_path(ais_attribute) do -%>
				<span class="glyphicon glyphicon-remove"></span>
				<% end -%>
			</td>
	  </tr>
		<% end %>
	</tbody>
</table>
	
<div class="panel panel-default">
	<div class="panel-footer">
		<%= paginate @ais_attributes %>
	</div>
</div>

app/views/ais_attributes/new.html.erb
<div class="page-header">
  <h2>New AIS Attribute</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_attributes_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_attribute_path, "Add New", "glyphicon-plus", class: "active" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
	<%= nav_tab_link_to show_import_ais_attributes_path, "Import", "glyphicon-import" %>
</ul>

<%= render 'form' %>

app/views/ais_attributes/show.html.erb
<div class="page-header">
  <h2>AIS Attribute</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_attributes_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_attribute_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to @ais_attribute, "Details", "glyphicon-info-sign", class: "active" %>
	<%= nav_tab_link_to edit_ais_attribute_path(@ais_attribute), "Edit", "glyphicon-pencil" %>
	<%= nav_tab_link_to are_you_sure_ais_attribute_path(@ais_attribute), "Delete", "glyphicon-remove" %>
	<%= nav_tab_link_to show_import_ais_attributes_path, "Import", "glyphicon-import" %>
</ul>

<%= render 'details' %>

app/views/ais_attributes/show_import.html.erb
<div class="page-header">
  <h2>Import AIS Attributes</h2>
</div>

<ul class="nav nav-tabs">
	<%= nav_tab_link_to ais_checklists_path, "List", "glyphicon-list" %>
	<%= nav_tab_link_to new_ais_checklist_path, "Add New", "glyphicon-plus" %>
	<%= nav_tab_link_to "#", "Details", "glyphicon-info-sign", class: "disabled" %>
	<%= nav_tab_link_to "#", "Edit", "glyphicon-pencil", class: "disabled" %>
	<%= nav_tab_link_to "#", "Delete", "glyphicon-remove", class: "disabled" %>
	<%= nav_tab_link_to show_import_ais_checklists_path, "Import", "glyphicon-import", class: "active" %>
</ul>

<div class="panel panel-default panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Warning! This will delete all records before importing.</h3>
  </div>
  <div class="panel-body">
		<%= form_tag import_ais_attributes_path, multipart: true, role: "form", class: "form-inline" do %>
			<div class="form-group">
				<%= file_field_tag :file %>
			</div>
			<button type="submit" class="btn btn-danger" name="commit"><span class="glyphicon glyphicon-import"></span> Import</button>
		<% end %>
	</div>
</div>